## Datasource Properties



spring:
  ## Uncomment the following block to switch to h2 database
  #  profiles:
  #    active: h2
  datasource:
    url: jdbc:mysql://localhost:3306/opentxt_notesapp
    username: root
    password: root

  ## Hibernate Properties
  jpa:
    hibernate:
      ddl-auto: update
    show_sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
